---
- hosts:                all
  become:               true
  vars_files:
    - vars/hostvars.yml

  tasks:

  - name:               "Create required directories ( /etc/letsencrypt )"
    file:
      path:             /etc/letsencrypt/{{ reqitems }}
      state:            directory
      owner:            root
      group:            root
      mode:             '0755'
    vars:
      reqitems:
        - account
        - certs
        - csrs
        - keys

  - name:               "Transfer script for generating a Let's Encrypt account key"
    copy:               src=files/generateacckey.sh dest=/tmp/scripts/ mode=0777

  - name:               "Execute script for generating a Let's Encrypt account key"
    command:             sh /tmp/scripts/generateacckey.sh

  - name:               "copy and generate Let's Encrypt private key"
    script:             /files/genprivatekey.sh

  - name:               "copy and Generate Let's Encrypt CSR"
    script:             /files/gencsr.sh

  - name:               "Begin Encryption"
    letsencrypt:
      acme_directory:   "{{ acme_directory }}"
      acme_version:     "{{ acme_version }}"
      account_key_src:  "{{ letsencrypt_account_key }}"
      account_email:    "{{ acme_email }}"
      terms_agreed:     1
      challenge:        "{{ acme_challenge_type }}"
      csr:              "{{ letsencrypt_csrs_dir }}/{{ domain_name }}.csr"
      dest:             "{{ letsencrypt_certs_dir }}/{{ domain_name }}.crt"
      fullchain_dest:   "{{ letsencrypt_certs_dir }}/fullchain_{{ domain_name }}.crt"
      remaining_days:   91
    register:           acme_challenge_your_domain

  - name:               "Create .well-known/acme-challenge directory"
    file:
      path:             /var/www/html/.well-known/acme-challenge
      state:            directory
      owner:            root
      group:            root
      mode:             u=rwx,g=rx,o=rx

  - name:               "Implement http-01 challenge files"
    copy:
      content:          "{{ acme_challenge_your_domain['challenge_data'][item]['http-01']['resource_value'] }}"
      dest:             "/var/www/html/{{ acme_challenge_your_domain['challenge_data'][item]['http-01']['resource'] }}"
      owner:            root
      group:            root
      mode:             u=rw,g=r,o=r
    with_items:
    - "{{ domain_name }}"
    - "www.{{ domain_name }}"

  - name:               "Complete Let's Encrypt challenges"
    letsencrypt:
      acme_directory:   "{{ acme_directory }}"
      acme_version:     "{{ acme_version }}"
      account_key_src:  "{{ letsencrypt_account_key }}"
      account_email:    "{{ acme_email }}"
      challenge:        "{{ acme_challenge_type }}"
      csr:              "{{ letsencrypt_csrs_dir }}/{{ domain_name }}.csr"
      dest:             "{{ letsencrypt_certs_dir }}/{{ domain_name }}.crt"
      chain_dest:       "{{ letsencrypt_certs_dir }}/chain_{{ domain_name }}.crt"
      fullchain_dest:   "{{ letsencrypt_certs_dir }}/fullchain_{{ domain_name }}"
      data:             "{{ acme_challenge_your_domain }}"
