##################################################
# Wordpress RemoteDB playbook for CentOS by rk
##################################################
---
- hosts:                 all
  become:                true
  vars_files:
    - vars/rdbdefault.yml

  tasks:

    - name:              Install prerequisities
      yum:
        name:            "{{ dbpacks }}"
      vars:
        dbpacks:
         - mariadb-server
         - MySQL-python

    - name:              Start MariaDB
      service:           name=mariadb state=started

    - name:              Set bind address for remote access
      template:
        src:             "files/mariadb-bind-cnf.j2"
        dest:            "/etc/my.cnf.d/server.cnf"

    - name:              Is root password set?
      command:           mysql -u root --execute "SELECT NOW()"
      register:          is_root_password_set
      ignore_errors:     yes

    - name:              Set root password
      mysql_user:        user=root password="{{ mariadb_root_pw }}" host=localhost
      when:              is_root_password_set.rc == 0

    - name:              Inform user of mysql root password
      debug:
        msg:             "MariaDB root password was set to {{ mariadb_root_pw }}"
      when:              is_root_password_set.rc == 0

    - name:              Create database
      mysql_db:
        name:            "{{ db_name }}"
        login_user:      root
        login_password:  "{{ mariadb_root_pw }}"
        login_host:      localhost
        state:           present

    - name:              Create local user for the DB
      mysql_user:
        name:            "{{ db_user }}"
        password:        "{{ db_user_pw }}"
        # priv:          '{{ db_name }}.*:ALL,GRANT'
        priv:            '*.*:ALL,GRANT'
        login_user:      root
        login_password:  "{{ mariadb_root_pw }}"
        state:           present

    # - name:              Create remote user for the wordpress DB
    #   mysql_user:
    #     name:            "{{ db_user }}"
    #     host:            "{{ webserver_ip }}"
    #     password:        "{{ db_user_pw }}"
    #     # priv:          '{{ db_name }}.*:ALL,GRANT'
    #     priv:            '*.*:ALL,GRANT'
    #     login_user:      root
    #     login_password:  "{{ mariadb_root_pw }}"
    #     state:           present

    - name:              Restart mariadb
      service:
        name:            mariadb
        state:           restarted
