---
- hosts:            all
  become:           true
  vars_files:
    - scripts/autorenew.sh

  tasks:

    - name:         Install prereq
      yum:          name=yum-utils state=latest

    - name:         Enable optional channel
      command:      "yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional"

    - name:         Install Certbot for apache
      yum:
        name:       "{{ certpacks }}"
        state:      latest
      vars:
        certpacks:
         - certbot
         - python2-certbot-apache

    - name:         Get certificates
      command:      "certbot certonly --apache"

    - name:         Set up autorenewal
      script:       scripts/autorenew.sh
