---
- hosts:            all
  become:           true
  vars_files:
    - vars/vars.yml

  tasks:

    - name:         Install prereq
      yum:          name=yum-utils state=latest

    - name:         Enable optional channel
      command:      "yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional"

    - name:         Install Certbot apache package
      yum:
        name:       "{{ certpacks }}"
        state:      latest
      vars:
        certpacks:
         - certbot
         - python2-certbot-apache

    - name:         Check if certificate already exists.
      stat:
        path:       /etc/letsencrypt/live/{{ item.servername }}/cert.pem
      register:     letsencrypt_cert
      with_items:   "{{ apache_vhosts }}"

    # - name:         Stop services to allow certbot to generate a cert IF needed
    #   service:
    #     name:       "{{ services }}"
    #     state:      stopped
    #   vars:
    #     services:
    #      - nginx

    - name:         Get certificates IF it doesn't exist
      shell:        "certbot certonly --standalone --noninteractive --agree-tos --email {{ certbot_admin_email }} -d {{ item.item.servername }}"
      with_items:   "{{ letsencrypt_cert.results }}"
      when:         item.stat.exists == False

    # - name:         Start services IF needed
    #   service:
    #     name:       "{{ services }}"
    #     state:      started
    #   vars:
    #     services:
    #      - nginx

    - name:         Set up autorenewal
      script:       scripts/autorenew.sh
