##################################################
# Wordpress playbook for CentOS by rk v0.1
##################################################
---
- hosts:             all
  become:            true
  vars_files:
    - vars/wpdefault.yml

  tasks:

    - name:          Install prereq
      yum:           name=yum-utils state=latest

    - name:          Install mariadb packages
      yum:
        name:        "{{ dbpacks }}"
        state:       latest
      vars:
        dbpacks:
         - mariadb-server

    - name:          Install php prereq
      yum:
        name:        "{{ phppacks }}"
        state:       latest
      vars:
        phppacks:
        - epel-release
        - yum-utils

    - name:          Install wget
      yum:           name=wget state=latest

    - name:          Install release
      yum:           name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm

    - name:          Configure php
      shell:
        cmd:         sudo yum-config-manager --enable remi-php73

    - name:          Install php common modules
      yum:
        name:        "{{ phpmodules }}"
        state:       latest
      vars:
        phpmodules:
          - php
          - php-common
          - php-opcache
          - php-mcrypt
          - php-cli
          - php-gd
          - php-curl
          - php-mysql

    - name:          Extract wordpress TEST
      unarchive:
        src:         http://wordpress.org/latest.tar.gz
        dest:        /tmp/
        remote_src:  yes

    - name:          Clear yourhost contents IF exists
      file:
        state:       absent
        path:        /var/www/{{ http_host }}

    - name:          Copy wordpress to www/yourhost/
      copy:
        src:         /tmp/wordpress/
        dest:        /var/www/{{ http_host }}
        remote_src:  yes

    - name:          Create wp upload Directory
      file:
        path:        /var/www/{{ http_host }}/wp-content/uploads
        state:       directory
        owner:       apache
        group:       apache
        mode:        '0755'

    - name:          Create wp-config from sample
      template:
        src:         "files/wp-config-sample.j2"
        dest:        "/var/www/{{ http_host }}/wp-config.php"

    - name:          restarting apache
      service:
        name:        httpd
        state:       restarted
