- name:           httpd install
  hosts:          "{{ hosts }}"
  gather_facts:   true
  become:         true

  tasks:

    - name:       "Installing httpd"
      yum:        name=httpd state=latest

    - name:       "Add httpd to startup"
      systemd:
        name:     httpd
        enabled:  yes
        masked:   no

    - name:       "Start httpd"
      systemd:
        state:    started
        name:     httpd
