- name:          Install OTRS
  hosts:         "{{ hosts }}"
  gather_facts:  true
  become:        true

  tasks:

    - name:      "Install prereq (epel, wget)"
      yum:
        name:    "{{ prereq }}"
        state:   latest
      vars:
        prereq:
         - epel-release
         - wget

    - name:      "Install perl modules"
      command:   "yum install bash-completion "perl(Archive::Zip)" "perl(Crypt::SSLeay)" "perl(IO::Socket::SSL)" "perl(LWP::UserAgent)" "perl(Net::DNS)" "perl(Net::LDAP)" "perl(Template)" "perl(XML::LibXML)" "perl(XML::LibXSLT)" "perl(XML::Parser)" "perl(YAML::XS)" "perl(YAML::XS)" "perl(Authen::NTLM)" "perl(Mail::IMAPClient)" "perl(JSON::XS)" "perl(Encode::HanExtra)"  "perl(DBD::Pg)" "perl(Crypt::Eksblowfish::Bcrypt)" perl-core procmail -y"

    - name:      "Download & install OTRS distro"
      yum:       name=http://ftp.otrs.org/pub/otrs//RPMS/rhel/7/otrs-6.0.26-01.noarch.rpm

    # - name:    "Download OTRS distro"
    #   get_url:
    #     url:   http://ftp.otrs.org/pub/otrs//RPMS/rhel/7/otrs-6.0.26-01.noarch.rpm
    #     dest:  /tmp/otrs-6.0.26-01.noarch.rpm
    #     mode:  '0440'
    #
    # - name:    "Install OTRS"
    #   yum:
    #      name: /tmp/otrs-6.0.26-01.noarch.rpm
    #      state: present

    - name:      "Check missing modules"
      command:   "/opt/otrs/bin/otrs.CheckModules.pl"
