##################################################
# Apache playbook for CentOS by rk v0.1
##################################################
---
- hosts: all
  become: true
  vars_files:
    - sudopass
    - vars/default.yml
  tasks:

    - name: Install httpd
      yum: name=httpd state=latest
    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'
    - name: Copy index test page
      template:
        src: "files/index.html.j2"
        dest: "/var/www/{{ http_host }}/index.html"
    - name: Set up Apache virtualhost
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/httpd/conf/{{ http_conf }}"

    - name: "Firewall rule on on http for external connections"
      firewalld:
        zone: public
        service: http
        permanent: yes
        state: enabled

  handlers:
    - name: restart firewall
       service:
       name: firewalld
       state: restarted
   - name: Reload Apache
       service:
       name: httpd
       state: reloaded
   - name: Restart Apache
       service:
       name: httpd
       state: restarted
