##################################################
# GETDOCKER by rk
##################################################
---
- hosts:                 all
  become:                true
  vars_files:
    # - vars/wpdefault.yml

  tasks:

    - name:              Uninstall old versions
      yum:
        name:            "{{ oldmodules }}"
        state:           removed
      vars:
        oldmodules:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine

    - name:              Install prereq
      yum:
        name:            "{{ prereqs }}"
        state:           installed
      vars:
        prereqs:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2

    - name:              Set up stable repo
      yum_repository:
        name:            docker-ce
        description:     centos docker repo
        baseurl:         https://download.docker.com/linux/centos/docker-ce.repo
        gpgcheck:        no

    - name:              Install docker engine
      yum:
        name:            "{{ dockerinstall }}"
        state:           installed
      vars:
        dockerinstall:
          - docker-ce
          - docker-ce-cli
          - containerd.io

##gpg key check here if needed

    - name:              Start docker
      service:
        name:            docker
        state:           started

    - name:              Verify if docker is installed correctly
      docker_container:
        name:            hello-world
        image:           hello-world
        state:           started
